In [1]:
import numpy as np

In [2]:
a = np.array([1,2, 3])
print("One Dimentional:", a)

One Dimentional: [1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 2.0, 1.0]])
print("Two Dimentional:")
print(b)

Two Dimentional:
[[9. 8. 7.]
 [6. 2. 1.]]


In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 3)

In [6]:
# Get Type
b.dtype

dtype('float64')

In [7]:
# Get Size and Total Size
a.itemsize


8

In [8]:
a.size

3

# Accessing/Changing specific elements, rows, columns, etc

In [9]:


a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)



[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
# get Specific Element - [r, c]
a[1, 5]

np.int64(13)

In [11]:
# Get a specific row (1st row)
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
# Get a specific column (3rd column)
a[:, 2]


array([ 3, 10])

In [13]:
# Can also be done by [startindex:endindex:stepsize]
a[0, 1: 6: 2]

# 1. Start at second Index
# 2. Stop at 6th index
# 3. Step at 2th indexes everytime

array([2, 4, 6])

In [14]:
a[0, 1: -1: 2]

array([2, 4, 6])

In [15]:
# I can change the 13 i originally ascessed
a[1, 5] = 20

In [16]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
a[:, 2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [19]:
# 3D Example

In [27]:
b = np.array([[[1,2], [3, 4]],[[5, 6], [7, 8]]])

In [28]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
# Get specific element( work outside in)

In [30]:
b[0,1,1]

np.int64(4)

In [31]:
# Iniliaze Different Types of Arrays

In [36]:
# All 0s matrix
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
# All ones matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [38]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [39]:
# Random decimal number
np.random.rand(4, 2)

array([[0.53788517, 0.59151403],
       [0.4405956 , 0.87156885],
       [0.2131989 , 0.79508959],
       [0.21329304, 0.02315875]])

In [45]:
# random int values
np.random.randint(7, size=(3, 3))

array([[0, 4, 6],
       [2, 6, 0],
       [3, 6, 2]])

In [46]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
c = np.ones((5, 5), dtype='int')
c

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [52]:
c[2,2] = 9
c

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 9, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [55]:
c[1, 1:4] = 0

In [59]:
c[1:4, 1] = 0

In [61]:
c[3, 1:4] = 0

In [63]:
c[1:4, 3] = 0

In [64]:
c

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [66]:
# COPY
a


array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [68]:
b = a
b[0] = 100
a

array([[100, 100, 100, 100, 100, 100, 100],
       [  8,   9,   2,  11,  12,  20,  14]])

In [69]:
# so to prevent this
b = a.copy()